# This is a basic workflow to help you get started with Actions

name: Deploy Airlab UI

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: deploy_dist
      
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Dockerize Airlab UI
        with:
          image: arunsudhakar/airlab-demo
          tags: airlab-ui
          dockerfile: Dockerfile
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
